# Configuration for https://travis-ci.org/

language: go
go_import_path: blitiri.com.ar/go/dnss

go:
    - 1.9
    - stable
    - master

script:
    - go test ./...
    - go test -bench . ./...
    - go test -race -bench . ./...

