# Configuration for https://travis-ci.org/

language: go
go_import_path: blitiri.com.ar/go/dnss

go:
    - 1.7
    - 1.8
    - tip

script:
    - go test ./...
    - go test -bench . ./...
    - go test -race -bench . ./...

